FROM apache/airflow:2.9.3-python3.10


USER root

RUN apt-get update && apt-get install -y build-essential \
    && rm -rf /var/lib/apt/lists/*


USER airflow


RUN pip install --no-cache-dir \
    pandas \
    numpy \
    scikit-learn \
    xgboost \
    joblib \
    mlflow \
    prophet